apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitalapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vitalapp
  template:
    metadata:
      labels:
        app: vitalapp
    spec:
      containers:
        - name: vitalapp
          image: vitalapp-back:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
